name: Test

on: pull_request_target

permissions:
  pull-requests: write
  contents: write
  packages: read

jobs:
  failfailfail:
    runs-on: ubuntu-latest

    steps:
      - name: Intentionally failing step2
        run: exit 0
